// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using home_energy_api.Data;

#nullable disable

namespace home_energy_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("home_energy_api.Models.Db.Device", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescDevice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtInactivation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtRegistration")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdHouseUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameDevice")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDevice");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("home_energy_api.Models.Db.HouseBill", b =>
                {
                    b.Property<int>("IdHouseBill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseKWH")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdHouseUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthBill")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TariffBill")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValuePerKWH")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearBill")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHouseBill");

                    b.ToTable("houseBills");
                });

            modelBuilder.Entity("home_energy_api.Models.Db.HouseUser", b =>
                {
                    b.Property<int>("IdHouseUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeriodDaysReport")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("IdHouseUser");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("home_energy_api.Models.Db.ReportDevice", b =>
                {
                    b.Property<int>("IdReportDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtReport")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdDevice")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValueTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("IdReportDevice");

                    b.ToTable("reportDevices");
                });

            modelBuilder.Entity("home_energy_api.Models.Db.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtInactivation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DtRegistration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
